# This workflow will install Python dependencies, run tests and lint with a variety of Python versions and send a warning mail if any change in status variables breaks the tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Status Variables

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:


permissions:
  contents: write

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  find_artifact_id:
    runs-on: ubuntu-latest
    outputs:
      artifact_run_id: ${{ steps.find-id.outputs.artifact_run_id }}
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}


    - name: Get latest artifact run id
      id: find-id
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          ARTIFACT_RUN_ID=$(
            curl -s -H "Authorization: Bearer $GH_TOKEN" \
                 "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=50" |
            jq '.artifacts[] | select(.name=="svs") | .workflow_run.id' |
            head -n 1
          )
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> "$GITHUB_ENV"
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> "$GITHUB_OUTPUT"

  test:
    needs: find_artifact_id
    runs-on: windows-latest
    strategy:
      fail-fast: false


    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: "pip"
        cache-dependency-path: pyproject.toml

    - name: Checkout qudi core
      run: |
        cd ..
        git clone https://github.com/Ulm-IQO/qudi-core.git@pyside6-dev
        cd qudi-core
        python -m pip install --upgrade pip
        pip install -e .
        qudi-install-kernel
        cd ../qudi-iqo-modules

    - name: Install dependencies for iqo modules
      run: |
        pip install -e ".[dev-test]"

    - name: Test with pytest
      run: |
         pytest tests\test_reset_status_var.py


    - name: Download svs artifact
      if:  needs.find_artifact_id.outputs.artifact_run_id  != ''
      uses: actions/download-artifact@v4
      with:
        name: svs
        path: .github/workflow_utils
        run-id: ${{ needs.find_artifact_id.outputs.artifact_run_id }}
        github-token:  ${{ secrets.GITHUB_TOKEN }}

    - name: Extract artifacts
      if:  needs.find_artifact_id.outputs.artifact_run_id != ''
      working-directory: .github/workflow_utils
      run: |
       tar -x -f svs.zip

    - name: Compare status variables
      if: always()
      working-directory: .github/workflow_utils
      run: |
       python compare_status_vars.py

    - name: Upload status vars diff
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: status_vars_diff
        path: .github/workflow_utils/status_var_changes.txt

    - name:  save latest svs
      if: success()
      working-directory: .github/workflow_utils
      run: |
        python save_status_vars.py
        tar -a -c -f svs.zip saved_status_vars

    - name: Upload svs artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: svs
        path: .github/workflow_utils/svs.zip
