# This workflow will check for updates in Python dependencies, run tests and lint with a variety of Python versions and send a warning mail if something breaks
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 0 * * *'

permissions:
  contents: write

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Python matrix from pyproject.toml
        id: build
        run: |
          python .github/scripts/fetch_python_versions.py | jq .
        shell: bash

  check-package-updates:
    needs: make-matrix
    runs-on: ubuntu-latest
    outputs:
      updates-available: ${{ steps.check-updates.outputs.updates-available }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install script dependencies
      run:
        pip install requests packaging toml


    - name: Check for new package versions
      id: check-updates
      run: |
        git checkout workflow_save
        python workflow_utils/check_updates.py -v ${{ matrix.python-version }}
  
  test:
    needs: [make-matrix, check-package-updates]
    if: ${{ needs.check-package-updates.outputs.updates-available == 'true' }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
   
       
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: pyproject.toml

    - name: Checkout qudi core
      run: |
        cd ..
        git clone https://github.com/Ulm-IQO/qudi-core.git
        cd qudi-core
        python -m pip install --upgrade pip
        pip install -e .
        qudi-install-kernel
        cp pyproject.toml ../pyproject_core.toml
        cd ../qudi-iqo-modules
        cp pyproject.toml ../pyproject_iqo.toml

    - name: Install dependencies for iqo modules
      run: |
        pip install -e ".[dev-test]"

    - name: Test with pytest
      run: |
        pytest -s

    - name: Switch to test branch
      if: always()
      run: |
        git checkout workflow_save

    - name: Pip freeze
      if: failure()
      working-directory: workflow_utils
      run: |
        pip freeze | Out-File -Encoding UTF8 failed_reqs.txt

    - name: Compare pip freeze outputs
      if: failure()
      working-directory: workflow_utils
      run: |
       python compare_pip_freeze.py failed_reqs.txt reqs_${{ matrix.python-version }}.txt pip_freeze_diff_${{ matrix.python-version }}.txt

    - name: Upload pip freeze diff
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pip-freeze-diff-${{ matrix.python-version }}
        path: workflow_utils/pip_freeze_diff_${{ matrix.python-version }}.txt

    - name: send email in case of failure
      if: failure()
      working-directory: workflow_utils
      run: |
        python failure_email_req.py -p ${{ matrix.python-version }} -d pip_freeze_diff_${{ matrix.python-version }}.txt


    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Pip freeze on test success and commit latest deps
      if: success()
      run: |
        cd workflow_utils
        cp ../../pyproject_core.toml .
        cp ../../pyproject_iqo.toml .

        pip freeze | Out-File -Encoding UTF8 reqs_${{ matrix.python-version }}.txt
        git add --all
        git commit -m "updated reqs.txt to latest successful run"
        git pull --rebase
        git push --force-with-lease origin HEAD:workflow_save
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
