# This workflow will check for updates in Python dependencies, run tests and lint with a variety of Python versions and send a warning mail if something breaks
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Dependencies

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:


permissions:
  contents: write

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  make-matrix:
    runs-on: windows-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Python matrix from pyproject.toml
        id: build
        run: |
          python .github/workflow_utils/fetch_python_versions.py | jq .
        shell: bash

  check-package-updates:
    needs: make-matrix
    runs-on: ubuntu-latest
    outputs:
      updates-available: ${{ steps.check-updates.outputs.updates-available }}
      artifact_run_id: ${{ steps.find-id.outputs.artifact_run_id }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install script dependencies
      run:
        pip install requests packaging toml

    - name: Checkout qudi core
      run: |
        cd ..
        git clone https://github.com/Ulm-IQO/qudi-core.git@pyside6-dev

    - name: Get latest artifact run id
      id: find-id
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          ARTIFACT_RUN_ID=$(
            curl -s -H "Authorization: Bearer $GH_TOKEN" \
                 "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=50" |
            jq '.artifacts[] | select(.name=="reqs_${{ matrix.python-version }}") | .workflow_run.id' |
            head -n 1
          )
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> "$GITHUB_ENV"
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> "$GITHUB_OUTPUT"

    - name: Download reqs artifact
      if: env.artifact_run_id != ''
      uses: actions/download-artifact@v4
      with:
        name: reqs_${{ matrix.python-version }}
        path: .github/workflow_utils
        run-id: ${{ env.artifact_run_id }}
        github-token:  ${{ secrets.GITHUB_TOKEN }}


    - name: Check for new package versions
      id: check-updates
      working-directory: .github/workflow_utils
      run: |
        python check_updates.py -v ${{ matrix.python-version }}

  test:
    needs: [make-matrix, check-package-updates]
    if: ${{ needs.check-package-updates.outputs.updates-available == 'true' }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ${{ fromJson(needs.make-matrix.outputs.matrix) }}


    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: pyproject.toml

    - name: Checkout qudi core
      run: |
        cd ..
        git clone https://github.com/Ulm-IQO/qudi-core.git@pyside6-dev
        cd qudi-core
        python -m pip install --upgrade pip
        pip install -e .
        qudi-install-kernel
        cd ../qudi-iqo-modules

    - name: Install dependencies for iqo modules
      run: |
        pip install -e ".[dev-test]"

    - name: Test with pytest
      run: |
        pytest -s


    - name: Pip freeze
      working-directory: .github/workflow_utils
      run: |
        pip freeze | Out-File -Encoding UTF8 reqs_${{ matrix.python-version }}.txt

    - name: Download reqs artifact
      if: needs.check-package-updates.outputs.artifact_run_id != ''
      uses: actions/download-artifact@v4
      with:
        name: reqs_${{ matrix.python-version }}
        path: .github/workflow_utils/prev
        run-id:  ${{ needs.check-package-updates.outputs.artifact_run_id }}
        github-token:  ${{ secrets.GITHUB_TOKEN }}

    - name: Compare pip freeze outputs
      if: failure()
      working-directory: .github/workflow_utils
      run: |
       python compare_pip_freeze.py reqs_${{ matrix.python-version }}.txt prev/reqs_${{ matrix.python-version }}.txt pip_freeze_diff_${{ matrix.python-version }}.txt

    - name: Upload pip freeze diff
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pip-freeze-diff-${{ matrix.python-version }}
        path: .github/workflow_utils/pip_freeze_diff_${{ matrix.python-version }}.txt


    - name: Upload reqs artifact
      if: success()

      uses: actions/upload-artifact@v4
      with:
        name: reqs_${{ matrix.python-version }}
        path: .github/workflow_utils/reqs_${{ matrix.python-version }}.txt

